version: "3.7"
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - $JENKINS_PLUGIN/target/:/var/jenkins_home/plugins
# Uncomment environment variables based on your needs. Everything can be configured in jenkins /configure page as well.
    environment:
      - DATADOG_JENKINS_PLUGIN_REPORT_WITH=DSD
      - DATADOG_JENKINS_PLUGIN_COLLECT_BUILD_LOGS=false
  # Set `DATADOG_JENKINS_PLUGIN_TARGET_HOST` to `dogstatsd` or `datadog` based on the container you wish to use.
      - DATADOG_JENKINS_PLUGIN_TARGET_HOST=datadog
      - DATADOG_JENKINS_PLUGIN_TARGET_LOG_COLLECTION_PORT=10518
      - DATADOG_JENKINS_PLUGIN_TARGET_API_KEY=$JENKINS_PLUGIN_DATADOG_API_KEY
      - DATADOG_JENKINS_PLUGIN_EMIT_SECURITY_EVENTS=false
      - DATADOG_JENKINS_PLUGIN_INCLUDE_EVENTS="User Authenticated"

## Uncomment the section below to use the standalone DogStatsD server to send metrics to Datadog
#  dogstatsd:
#    image: datadog/dogstatsd:latest
#    environment:
#      - DD_API_KEY=$JENKINS_PLUGIN_DATADOG_API_KEY
#    ports:
#      - 8125:8125

## Uncomment the section below to use the whole Datadog Agent to send metrics (and logs) to Datadog.
## Note that it contains a DogStatsD server as well.
  datadog:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=$JENKINS_PLUGIN_DATADOG_API_KEY
      - DD_URL="https://dd.datad0g.com"
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    ports:
      - 8125:8125
      - 10518:10518
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - $JENKINS_PLUGIN/conf.yaml:/etc/datadog-agent/conf.d/jenkins.d/conf.yaml